fix defer_mail $reason.
ERROR: EOM callback error Can't locate object method "loginfo" via package "Mail::Milter::Authentication::Handler::RSpamD" at /usr/local/lib/perl5/site_perl/Mail/Milter/Authentication/Handler.pm line 1330, <$read> line 5858.

loginfo method does not exist in Mail::Milter::Authentication::Handler.
It exists in Mail::Milter::Authentication.
calling method may need to be modified.